# Generated by Django 4.1.6 on 2023-02-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_forecast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherparams',
            name='date_time',
        ),
    ]
