# Generated by Django 4.1.6 on 2023-02-09 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_forecast', '0002_remove_weatherparams_date_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeatherParams',
            new_name='WeatherModel',
        ),
    ]
